"use client";
import { useState } from "react";
import ThreadPreview from "./ThreadPreview";

function CopyButton({ text, label = "Copy" }) {
  const [copied, setCopied] = useState(false);
  function handleCopy() {
    navigator.clipboard?.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }
  return (
    <button
      onClick={handleCopy}
      className="px-3 py-1.5 bg-ink-700 hover:bg-ink-600 text-ink-200 text-xs rounded-lg transition-colors"
    >
      {copied ? "Copied ✓" : label}
    </button>
  );
}

export default function SharedOutput({ data, shareId }) {
  const { final_output, formatted_variants, created_at } = data;
  const [tab, setTab] = useState("native");

  const variants = formatted_variants || {};
  const tabs = [
    { id: "native",     label: "Original" },
    ...(variants.linkedin_variant    ? [{ id: "linkedin",   label: "LinkedIn" }]   : []),
    ...(variants.newsletter_paragraph ? [{ id: "newsletter", label: "Newsletter" }] : []),
  ];

  const currentContent =
    tab === "native"     ? final_output :
    tab === "linkedin"   ? variants.linkedin_variant :
    tab === "newsletter" ? variants.newsletter_paragraph :
    final_output;

  const isThread = (() => {
    try { const p = JSON.parse(final_output); return Array.isArray(p); } catch { return false; }
  })();

  const parsedDraft = (() => {
    if (!isThread) return null;
    try { return JSON.parse(final_output); } catch { return null; }
  })();

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="space-y-1">
        <div className="flex items-center gap-2">
          <span className="stage-pill bg-signal-teal/10 text-signal-teal border border-signal-teal/20">
            Shared output
          </span>
          {created_at && (
            <span className="text-xs text-ink-500">
              {new Date(created_at).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
            </span>
          )}
        </div>
        <p className="text-ink-400 text-xs font-mono">{shareId}</p>
      </div>

      {/* Format tabs */}
      {tabs.length > 1 && (
        <div className="flex gap-1 bg-ink-800/60 p-1 rounded-xl w-fit">
          {tabs.map(t => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`px-4 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                tab === t.id
                  ? "bg-ink-700 text-ink-100 shadow"
                  : "text-ink-400 hover:text-ink-200"
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>
      )}

      {/* Content */}
      <div className="glass rounded-2xl overflow-hidden">
        <div className="px-5 py-3 border-b border-ink-800/60 flex items-center justify-between">
          <span className="text-xs font-semibold text-ink-400 uppercase tracking-wide">
            {tab === "native" ? (isThread ? "Thread" : "Essay") : tabs.find(t => t.id === tab)?.label}
          </span>
          <div className="flex items-center gap-2">
            {variants.word_count && (
              <span className="text-xs text-ink-500">{variants.word_count.toLocaleString()} words</span>
            )}
            <CopyButton text={currentContent || ""} />
          </div>
        </div>
        <div className="p-5">
          {tab === "native" && parsedDraft ? (
            <ThreadPreview draft={parsedDraft} />
          ) : (
            <div className="text-ink-200 text-sm leading-relaxed whitespace-pre-wrap font-sans">
              {currentContent}
            </div>
          )}
        </div>
      </div>

      {/* Share this page */}
      <div className="flex items-center gap-3 text-xs text-ink-500">
        <span>Share this page:</span>
        <code className="bg-ink-800 px-3 py-1.5 rounded-lg text-signal-teal font-mono">
          {typeof window !== "undefined" ? window.location.href : ""}
        </code>
        <CopyButton
          text={typeof window !== "undefined" ? window.location.href : ""}
          label="Copy link"
        />
      </div>

      {/* Footer CTA */}
      <p className="text-ink-600 text-xs text-center pb-6">
        Generated by{" "}
        <a href="/" className="text-ink-400 hover:text-ink-200 transition-colors">Voice Agent</a>
        {" "}— research-grounded content in your authentic voice
      </p>
    </div>
  );
}
